# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: oscope 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "oscope"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["tduehr"]
  s.date = "2015-02-03"
  s.description = "SCPI (IEEE 488.2) interface. Only the Rigol DS1102D oscilloscope is implemented currently. All SCPI interfaces *should* be supported."
  s.email = "tduehr@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "oscope.gemspec",
    "oscope/relation.rb",
    "oscope/relation/base.rb",
    "oscope/relation/channel.rb",
    "oscope/relation/group.rb",
    "oscope/relation/key.rb",
    "oscope/relation/query.rb",
    "oscope/relation/write.rb",
    "oscope/rigol/ds1102d.rb"
  ]
  s.homepage = "http://github.com/tduehr/oscope"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "SCPI command interface"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<airby>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<ffi>, ["~> 1.9.6"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<airby>, ["~> 0.1.0"])
      s.add_dependency(%q<ffi>, ["~> 1.9.6"])
      s.add_dependency(%q<yard>, ["~> 0.8.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<airby>, ["~> 0.1.0"])
    s.add_dependency(%q<ffi>, ["~> 1.9.6"])
    s.add_dependency(%q<yard>, ["~> 0.8.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

